### ISSUE TITLE
Stopped working on Safari 13

### ISSUE THREAD

**Issue by iSuslov** [GoogleChromeLabs/shadow-selection-polyfill#6]
On Safari 13 returned range is always null. It can be reproduced in demo: 
https://googlechromelabs.github.io/shadow-selection-polyfill/demo.html

**Comment by iSuslov** [comment]
For anyone who interested in a workaround for this(not ideal for sure), I just removed return statement on line #316

>    //return {range: null, mode: 'none'};

**Comment by samthor** [comment]
Thanks, I've not had time to look at this yet. I'll take a look.

**Comment by ziulev** [comment]
Any update?

**Comment by samthor** [comment]
I've just released version 1.1.0 which changes the approach a bit, and fixes the Safari 13 issue. Please try it out!
